import rulesJson from "../config/rules.json";
import {
  RulesFileSchema,
  isPublished,
  type Category,
  type CategoryGate,
  type CheckableEvidence,
  type Gate,
  type GeneralGate,
  type PartyField,
  type PartyQuestion,
  type PublishedGate,
  type Question,
  type RulesFile,
} from "./types";

/**
 * Parsed and validated ONCE at import. If legal breaks rules.json
 * this throws at startup with the gate id and field in the message —
 * not mid-demo. Needs "resolveJsonModule": true in tsconfig.json
 * (create-next-app default).
 */
export const rules: RulesFile = RulesFileSchema.parse(rulesJson);

/** General gates that are ready to evaluate. */
export const publishedGeneralGates: GeneralGate[] = rules.generalGates.filter(isPublished);

/** Category gates for one claim type that are ready to evaluate. */
export function publishedCategoryGates(categoryId: string): CategoryGate[] {
  return rules.categoryGates.filter((g) => g.category === categoryId && isPublished(g));
}

/**
 * Categories the UI may offer. Derived, never declared separately:
 * a category with zero published gates is not offered, so the demo
 * cannot route a claimant into an empty rule set.
 */
export function supportedCategories(): Category[] {
  return rules.categories.filter((c) => publishedCategoryGates(c.id).length > 0);
}

/**
 * Turns gates into the form the UI renders. One question per distinct
 * field — two gates on claimAmount produce one input, not two.
 */
export function toQuestions(gates: Gate[]): Question[] {
  const byField = new Map<string, Question>();
  for (const g of gates.filter(isPublished)) {
    const existing = byField.get(g.field);
    if (existing) {
      existing.gateIds.push(g.id);
      continue;
    }
    byField.set(g.field, {
      field: g.field,
      question: g.question,
      answerType: g.answerType,
      options: g.options,
      gateIds: [g.id],
    });
  }
  return [...byField.values()];
}

export const generalQuestions: Question[] = toQuestions(publishedGeneralGates);
export function categoryQuestions(categoryId: string): Question[] {
  return toQuestions(publishedCategoryGates(categoryId));
}

/* ============================================================
 * EVIDENCE LAYER (Sprint 2, Feature 2)
 * ============================================================ */

/** Every published gate, both phases. The closed world the LLM may refer to. */
export const publishedGates: PublishedGate[] = [
  ...rules.generalGates,
  ...rules.categoryGates,
].filter(isPublished);

/**
 * Gate ids the LLM is allowed to name. llm/schema.ts turns this into a
 * z.enum, so the model has no field in which to express a gate that
 * doesn't exist — it cannot invent a legal issue.
 */
export const publishedGateIds: string[] = publishedGates.map((g) => g.id);

const gatesById = new Map<string, PublishedGate>(publishedGates.map((g) => [g.id, g]));

/**
 * Lookup for the post-call join. `source` and `plainExplanation` are
 * attached back to a finding by gateId here — never generated by the model.
 */
export function gateById(id: string): PublishedGate | undefined {
  return gatesById.get(id);
}

/** A published gate legal has said a document could actually speak to. */
export type CheckableGate = PublishedGate & { evidence: CheckableEvidence };

function isCheckable(g: PublishedGate): g is CheckableGate {
  return g.evidence?.checkable === true;
}

/**
 * The gates that go into the prompt payload. Filtered by *verifiability*,
 * not severity — a claimant who is confidently wrong hides in the PASS set,
 * so passed gates must be in scope too (DECISIONS.md §Evidence).
 *
 * Scoped to one claim: general gates plus the chosen category's. Omit the
 * category to get every checkable gate.
 */
export function checkableGates(categoryId?: string): CheckableGate[] {
  return publishedGates
    .filter((g) => g.scope === "general" || categoryId === undefined || g.category === categoryId)
    .filter(isCheckable);
}

/** Party & filing intake fields ready to show (Sprint 2). */
export const publishedPartyFields: PartyField[] = rules.partyFields.filter((f) => f.status === "published");

/** Turns published party fields into what the UI renders. */
export function partyQuestions(): PartyQuestion[] {
  return publishedPartyFields.map((f) => ({
    field: f.field,
    question: f.question,
    answerType: f.answerType,
    options: f.options,
    dependsOn: f.dependsOn,
  }));
}